trigger:
  branches:
    include:
      - main

variables:
  - name: appName
    value: goodwe-api
  - group: prod-back-goodwe-api

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - template: './build-application.yml'
            parameters:
              appName: '$(appName)'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: tar
              archiveFile: $(Build.ArtifactStagingDirectory)/$(appName).tar.gz
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/$(appName).tar.gz
            artifact: drop

  - stage: RenderDeploy
    displayName: Deploy to Render
    dependsOn: Build
    jobs:
      - job: TriggerDeploy
        displayName: Trigger Render Deploy Hook
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                if [ -z "$(renderDeployHookUrl)" ]; then
                  echo "Variável renderDeployHookUrl não está configurada no grupo de variáveis!"
                  exit 1
                fi
                echo "Disparando o deploy no Render..."
                curl -X POST "$(renderDeployHookUrl)"
                echo "Deploy iniciado com sucesso!"
            displayName: 'Trigger Render Deployment'
