services:
  api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: api 
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlserver://sqlserver:1433;database=base_nest_api;user=${DB_USER:-sa};password=${DB_PASSWORD:-YourStrongPassword123!};encrypt=true;trustServerCertificate=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    labels:
      service: "api-name"

  sqlserver:
    build:
      context: ./docker/
      dockerfile: sqlserver/Dockerfile
    user: root
    container_name: sqlserver
    mem_limit: 2G
    memswap_limit: 4G
    cpus: 2
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    environment:
      - MSSQL_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - .docker/sqlserver:/var/opt/mssql
    ports:
      - "${DB_PORT:-1433}:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -C -U "${DB_USER}" -Q "SELECT 1"',
        ]
      interval: 10s
      retries: 5
      timeout: 3s

  redis:
    build: ./docker/redis
    container_name: redis
    restart: always
    mem_limit: 2.5G
    memswap_limit: 4G
    cpus: 2
    env_file:
      - path: .env
        required: true
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_CACHE_PORT:-27002}:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      retries: 5
      timeout: 3s

volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local