services:
  api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: api 
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${DB_USER:-root}:${DB_PASSWORD:-YourStrongPassword123!}@mysql:3306/base_nest_api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    labels:
      service: "api-name"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=base_nest_api
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 5
      timeout: 3s

  redis:
    build: ./docker/redis
    container_name: redis
    restart: always
    mem_limit: 2.5G
    memswap_limit: 4G
    cpus: 2
    env_file:
      - path: .env
        required: true
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_CACHE_PORT:-27002}:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      retries: 5
      timeout: 3s

volumes:
  mysql_data:
  redis_data:
    driver: local